/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/2aErYr0K9VsBnAdK/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#5bf0fe"]} />
      <group {...props} dispose={null}>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.8}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1165.7155}
          shadow-camera-right={1165.7155}
          shadow-camera-top={1165.7155}
          shadow-camera-bottom={-1165.7155}
          position={[681.15, 772.72, 229.06]}
        />
        <mesh
          name="water"
          geometry={nodes.water.geometry}
          material={materials.water}
          receiveShadow
          position={[59.69, 60.75, 76.9]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.94, 1.32, 1]}
        />
        <group name="bunny" position={[138.75, 176.38, 186.97]}>
          <mesh
            name="Rectangle 9"
            geometry={nodes["Rectangle 9"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[21.58, 32.81, 7.15]}
            rotation={[0, 0, -0.17]}
            scale={1}
          />
          <mesh
            name="Rectangle 6"
            geometry={nodes["Rectangle 6"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[-20.89, 35.54, 7.15]}
          />
          <mesh
            name="Cube 6"
            geometry={nodes["Cube 6"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[33.67, -20.91, 28.45]}
          />
          <mesh
            name="Cube 12"
            geometry={nodes["Cube 12"].geometry}
            material={materials["white-2"]}
            castShadow
            receiveShadow
            position={[25.45, -50.78, -29.06]}
            scale={[1.23, 1, 1.44]}
          />
          <mesh
            name="Cube 121"
            geometry={nodes["Cube 121"].geometry}
            material={materials["white-2"]}
            castShadow
            receiveShadow
            position={[-26.87, -50.78, -29.06]}
            scale={[1.23, 1, 1.44]}
          />
          <mesh
            name="Cube 8"
            geometry={nodes["Cube 8"].geometry}
            material={materials["white-2"]}
            castShadow
            receiveShadow
            position={[25.45, -50.78, 18.02]}
            scale={[1.23, 1, 1.44]}
          />
          <mesh
            name="Cube 7"
            geometry={nodes["Cube 7"].geometry}
            material={materials["white-2"]}
            castShadow
            receiveShadow
            position={[-26.87, -50.78, 18.02]}
            scale={[1.23, 1, 1.44]}
          />
          <mesh
            name="Cube 15"
            geometry={nodes["Cube 15"].geometry}
            material={materials["white-2"]}
            castShadow
            receiveShadow
            position={[22.84, 39.77, -0.5]}
            rotation={[0, 0, -0.17]}
            scale={[1, 1, 1.36]}
          />
          <mesh
            name="Cube 14"
            geometry={nodes["Cube 14"].geometry}
            material={materials["white-2"]}
            castShadow
            receiveShadow
            position={[-20.62, 42.62, -0.5]}
            scale={[1, 1, 1.36]}
          />
          <mesh
            name="Cube 5"
            geometry={nodes["Cube 5"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[-33.74, -20.91, 28.45]}
          />
          <mesh
            name="Rectangle 7"
            geometry={nodes["Rectangle 7"].geometry}
            material={materials["Rectangle 7 Material"]}
            castShadow
            receiveShadow
            position={[20.9, 1.3, 35.4]}
          />
          <mesh
            name="Rectangle 11"
            geometry={nodes["Rectangle 11"].geometry}
            material={materials.red}
            castShadow
            receiveShadow
            position={[1.75, -16.97, 35.4]}
          />
          <mesh
            name="Rectangle 10"
            geometry={nodes["Rectangle 10"].geometry}
            material={materials.red}
            castShadow
            receiveShadow
            position={[1.75, -11.05, 35.4]}
          />
          <mesh
            name="Rectangle 61"
            geometry={nodes["Rectangle 61"].geometry}
            material={materials["Rectangle 61 Material"]}
            castShadow
            receiveShadow
            position={[-20.44, 1.3, 35.4]}
          />
          <mesh
            name="Cube 2"
            geometry={nodes["Cube 2"].geometry}
            material={materials["white-2"]}
            castShadow
            receiveShadow
            position={[-0.11, -11.36, -5.1]}
          />
        </group>
        <group name="gold" position={[275.19, 158.26, 13.03]}>
          <group name="golden 3" position={[482.24, 0, -187.63]}>
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials["Cylinder Material"]}
              castShadow
              receiveShadow
              position={[0, 0, -2.05]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.4, 0.22, 0.4]}
            />
            <mesh
              name="$"
              geometry={nodes.$.geometry}
              material={materials["$ Material"]}
              castShadow
              receiveShadow
              position={[-6.7, -9, -2.85]}
              scale={[0.4, 0.4, 0.32]}
            />
            <mesh
              name="$1"
              geometry={nodes.$1.geometry}
              material={materials["$1 Material"]}
              castShadow
              receiveShadow
              position={[-6.7, -9, 1.49]}
              scale={[0.4, 0.4, 0.32]}
            />
          </group>
          <group name="golden 2" position={[-482.24, 0, 187.63]}>
            <mesh
              name="Cylinder1"
              geometry={nodes.Cylinder1.geometry}
              material={materials["Cylinder1 Material"]}
              castShadow
              receiveShadow
              position={[0, 0, -2.05]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.4, 0.22, 0.4]}
            />
            <mesh
              name="$2"
              geometry={nodes.$2.geometry}
              material={materials["$2 Material"]}
              castShadow
              receiveShadow
              position={[-6.7, -9, -2.85]}
              scale={[0.4, 0.4, 0.32]}
            />
            <mesh
              name="$3"
              geometry={nodes.$3.geometry}
              material={materials["$3 Material"]}
              castShadow
              receiveShadow
              position={[-6.7, -9, 1.49]}
              scale={[0.4, 0.4, 0.32]}
            />
          </group>
          <group name="golden" position={[-402.75, 0, 187.63]}>
            <mesh
              name="Cylinder2"
              geometry={nodes.Cylinder2.geometry}
              material={materials["Cylinder2 Material"]}
              castShadow
              receiveShadow
              position={[0, 0, -2.05]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.4, 0.22, 0.4]}
            />
            <mesh
              name="$4"
              geometry={nodes.$4.geometry}
              material={materials["$4 Material"]}
              castShadow
              receiveShadow
              position={[-6.7, -9, -2.85]}
              scale={[0.4, 0.4, 0.32]}
            />
            <mesh
              name="$5"
              geometry={nodes.$5.geometry}
              material={materials["$5 Material"]}
              castShadow
              receiveShadow
              position={[-6.7, -9, 1.49]}
              scale={[0.4, 0.4, 0.32]}
            />
          </group>
        </group>
        <group name="road" position={[155.43, 123.37, 165.22]}>
          <mesh
            name="10"
            geometry={nodes["10"].geometry}
            material={materials["10 Material"]}
            castShadow
            receiveShadow
            position={[-283.74, -0.32, 39.43]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="9"
            geometry={nodes["9"].geometry}
            material={materials["9 Material"]}
            castShadow
            receiveShadow
            position={[-361.61, -0.32, 39.43]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="8"
            geometry={nodes["8"].geometry}
            material={materials["8 Material"]}
            castShadow
            receiveShadow
            position={[-440.08, -0.32, 39.43]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="7"
            geometry={nodes["7"].geometry}
            material={materials["7 Material"]}
            castShadow
            receiveShadow
            position={[-518.93, -0.32, 39.43]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="22"
            geometry={nodes["22"].geometry}
            material={materials.road}
            castShadow
            receiveShadow
            position={[447.78, -1.37, 346.58]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="21"
            geometry={nodes["21"].geometry}
            material={materials.road}
            castShadow
            receiveShadow
            position={[370.55, -1.37, 346.58]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="20"
            geometry={nodes["20"].geometry}
            material={materials["20 Material"]}
            castShadow
            receiveShadow
            position={[525.58, -1.37, -111.44]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="19"
            geometry={nodes["19"].geometry}
            material={materials["19 Material"]}
            castShadow
            receiveShadow
            position={[597.4, -1.37, -184.01]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="18"
            geometry={nodes["18"].geometry}
            material={materials.road}
            castShadow
            receiveShadow
            position={[597.4, -1.37, -261.98]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="17"
            geometry={nodes["17"].geometry}
            material={materials.road}
            castShadow
            receiveShadow
            position={[597.4, -1.37, -339.81]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="16"
            geometry={nodes["16"].geometry}
            material={materials["16 Material"]}
            castShadow
            receiveShadow
            position={[519.82, -1.37, -339.81]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="15"
            geometry={nodes["15"].geometry}
            material={materials["15 Material"]}
            castShadow
            receiveShadow
            position={[442.04, -1.37, -339.81]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="14"
            geometry={nodes["14"].geometry}
            material={materials["14 Material"]}
            castShadow
            receiveShadow
            position={[364.19, -1.37, -339.81]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="13"
            geometry={nodes["13"].geometry}
            material={materials["13 Material"]}
            castShadow
            receiveShadow
            position={[286.78, -1.37, -339.81]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="12"
            geometry={nodes["12"].geometry}
            material={materials.road}
            castShadow
            receiveShadow
            position={[208.73, -1.37, -339.81]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="11"
            geometry={nodes["11"].geometry}
            material={materials.road}
            castShadow
            receiveShadow
            position={[52.4, -1.37, -339.81]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="6"
            geometry={nodes["6"].geometry}
            material={materials["6 Material"]}
            castShadow
            receiveShadow
            position={[-597.4, -0.32, 39.43]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="5"
            geometry={nodes["5"].geometry}
            material={materials["5 Material"]}
            castShadow
            receiveShadow
            position={[-597.4, -0.32, -38.63]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="3"
            geometry={nodes["3"].geometry}
            material={materials["3 Material"]}
            castShadow
            receiveShadow
            position={[-596.66, -1.22, -195.01]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="4"
            geometry={nodes["4"].geometry}
            material={materials["4 Material"]}
            castShadow
            receiveShadow
            position={[-596.66, -1.22, -116.65]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="2"
            geometry={nodes["2"].geometry}
            material={materials.road}
            castShadow
            receiveShadow
            position={[-595.66, -1.22, -273.18]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="1"
            geometry={nodes["1"].geometry}
            material={materials.road}
            castShadow
            receiveShadow
            position={[-674.12, -1.22, -273.18]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="water-wite" position={[29.04, 63.7, 141.29]}>
          <mesh
            name="Rectangle 25"
            geometry={nodes["Rectangle 25"].geometry}
            material={materials["water foam"]}
            castShadow
            receiveShadow
            position={[768.36, 0.39, 743.26]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 26"
            geometry={nodes["Rectangle 26"].geometry}
            material={materials["water foam"]}
            castShadow
            receiveShadow
            position={[-822.28, 0.39, 419.31]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 24"
            geometry={nodes["Rectangle 24"].geometry}
            material={materials["water foam"]}
            castShadow
            receiveShadow
            position={[-165.38, 0.39, 504.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 23"
            geometry={nodes["Rectangle 23"].geometry}
            material={materials["water foam"]}
            castShadow
            receiveShadow
            position={[149.8, 0.39, 635.99]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Shape 16"
            geometry={nodes["Shape 16"].geometry}
            material={materials["water foam"]}
            castShadow
            receiveShadow
            position={[-1069.81, -0.39, -374.65]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="flower" position={[43.07, 133.76, 255.44]}>
          <group
            name="Group 28"
            position={[564.62, 0, 404.95]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1}
          >
            <mesh
              name="Cube 4"
              geometry={nodes["Cube 4"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0.01, -1.32, 5.41]}
            />
            <mesh
              name="Cube 3"
              geometry={nodes["Cube 3"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[-1.37, -4.92, -4.91]}
            />
            <mesh
              name="Cube 21"
              geometry={nodes["Cube 21"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0, -4.92, 0.61]}
            />
            <mesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials.flower}
              castShadow
              receiveShadow
              position={[0, 7.92, 0.61]}
            />
          </group>
          <group
            name="Group 27"
            position={[481.6, 0, 179.27]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1}
          >
            <mesh
              name="Cube 41"
              geometry={nodes["Cube 41"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0.01, -1.32, 5.41]}
            />
            <mesh
              name="Cube 31"
              geometry={nodes["Cube 31"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[-1.37, -4.92, -4.91]}
            />
            <mesh
              name="Cube 22"
              geometry={nodes["Cube 22"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0, -4.92, 0.61]}
            />
            <mesh
              name="Cube1"
              geometry={nodes.Cube1.geometry}
              material={materials.flower}
              castShadow
              receiveShadow
              position={[0, 7.92, 0.61]}
            />
          </group>
          <group
            name="Group 26"
            position={[407.97, 0, 179.27]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1}
          >
            <mesh
              name="Cube 42"
              geometry={nodes["Cube 42"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0.01, -1.32, 5.41]}
            />
            <mesh
              name="Cube 32"
              geometry={nodes["Cube 32"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[-1.37, -4.92, -4.91]}
            />
            <mesh
              name="Cube 23"
              geometry={nodes["Cube 23"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0, -4.92, 0.61]}
            />
            <mesh
              name="Cube2"
              geometry={nodes.Cube2.geometry}
              material={materials.flower}
              castShadow
              receiveShadow
              position={[0, 7.92, 0.61]}
            />
          </group>
          <group
            name="Group 25"
            position={[-557.94, 0, -51.35]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1}
          >
            <mesh
              name="Cube 43"
              geometry={nodes["Cube 43"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0.01, -1.32, 5.41]}
            />
            <mesh
              name="Cube 33"
              geometry={nodes["Cube 33"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[-1.37, -4.92, -4.91]}
            />
            <mesh
              name="Cube 24"
              geometry={nodes["Cube 24"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0, -4.92, 0.61]}
            />
            <mesh
              name="Cube3"
              geometry={nodes.Cube3.geometry}
              material={materials.flower}
              castShadow
              receiveShadow
              position={[0, 7.92, 0.61]}
            />
          </group>
          <group
            name="Group 19"
            position={[-285.17, 0, -329.82]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1}
          >
            <mesh
              name="Cube 44"
              geometry={nodes["Cube 44"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0.01, -1.32, 5.41]}
            />
            <mesh
              name="Cube 34"
              geometry={nodes["Cube 34"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[-1.37, -4.92, -4.91]}
            />
            <mesh
              name="Cube 25"
              geometry={nodes["Cube 25"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0, -4.92, 0.61]}
            />
            <mesh
              name="Cube4"
              geometry={nodes.Cube4.geometry}
              material={materials.flower}
              castShadow
              receiveShadow
              position={[0, 7.92, 0.61]}
            />
          </group>
          <group
            name="Group 17"
            position={[275.82, 0, -95.93]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1}
          >
            <mesh
              name="Cube 45"
              geometry={nodes["Cube 45"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0.01, -1.32, 5.41]}
            />
            <mesh
              name="Cube 35"
              geometry={nodes["Cube 35"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[-1.37, -4.92, -4.91]}
            />
            <mesh
              name="Cube 26"
              geometry={nodes["Cube 26"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0, -4.92, 0.61]}
            />
            <mesh
              name="Cube5"
              geometry={nodes.Cube5.geometry}
              material={materials.flower}
              castShadow
              receiveShadow
              position={[0, 7.92, 0.61]}
            />
          </group>
          <group
            name="Group 20"
            position={[-244.93, 0, -291.67]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1}
          >
            <mesh
              name="Cube 46"
              geometry={nodes["Cube 46"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0.01, -1.32, 5.41]}
            />
            <mesh
              name="Cube 36"
              geometry={nodes["Cube 36"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[-1.37, -4.92, -4.91]}
            />
            <mesh
              name="Cube 27"
              geometry={nodes["Cube 27"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0, -4.92, 0.61]}
            />
            <mesh
              name="Cube6"
              geometry={nodes.Cube6.geometry}
              material={materials.flower}
              castShadow
              receiveShadow
              position={[0, 7.92, 0.61]}
            />
          </group>
          <group
            name="Group 191"
            position={[-177.28, 0, -329.82]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1}
          >
            <mesh
              name="Cube 47"
              geometry={nodes["Cube 47"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0.01, -1.32, 5.41]}
            />
            <mesh
              name="Cube 37"
              geometry={nodes["Cube 37"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[-1.37, -4.92, -4.91]}
            />
            <mesh
              name="Cube 28"
              geometry={nodes["Cube 28"].geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[0, -4.92, 0.61]}
            />
            <mesh
              name="Cube7"
              geometry={nodes.Cube7.geometry}
              material={materials.flower}
              castShadow
              receiveShadow
              position={[0, 7.92, 0.61]}
            />
          </group>
        </group>
        <group name="gress-2" position={[-220.17, 107.24, 280.2]}>
          <mesh
            name="Rectangle 71"
            geometry={nodes["Rectangle 71"].geometry}
            material={materials.grass}
            castShadow
            receiveShadow
            position={[-600.94, -22.13, -413.92]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 91"
            geometry={nodes["Rectangle 91"].geometry}
            material={materials.grass}
            castShadow
            receiveShadow
            position={[600.94, 7.95, 450.42]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 8"
            geometry={nodes["Rectangle 8"].geometry}
            material={materials.grass}
            castShadow
            receiveShadow
            position={[-4.38, 7.95, 77.64]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 27"
            geometry={nodes["Rectangle 27"].geometry}
            material={materials.grass}
            castShadow
            receiveShadow
            position={[-79.51, -15.53, 74.59]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 62"
            geometry={nodes["Rectangle 62"].geometry}
            material={materials.grass}
            castShadow
            receiveShadow
            position={[-376.93, -15.53, 155.29]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 111"
            geometry={nodes["Rectangle 111"].geometry}
            material={materials.grass}
            castShadow
            receiveShadow
            position={[594.15, 12.79, -114.37]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 4"
            geometry={nodes["Rectangle 4"].geometry}
            material={materials.grass}
            castShadow
            receiveShadow
            position={[511.65, 12.79, 77.31]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="gress-3" position={[115.58, 121.23, 57.29]}>
          <mesh
            name="Rectangle 19"
            geometry={nodes["Rectangle 19"].geometry}
            material={materials["gress-3"]}
            castShadow
            receiveShadow
            position={[765.03, 0.3, 380.96]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 18"
            geometry={nodes["Rectangle 18"].geometry}
            material={materials["gress-3"]}
            castShadow
            receiveShadow
            position={[-54.74, -5.3, 370.68]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 17"
            geometry={nodes["Rectangle 17"].geometry}
            material={materials["gress-3"]}
            castShadow
            receiveShadow
            position={[-741.3, 0.21, 188.37]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 16"
            geometry={nodes["Rectangle 16"].geometry}
            material={materials["gress-3"]}
            castShadow
            receiveShadow
            position={[-668.5, 0.21, -319.73]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 15"
            geometry={nodes["Rectangle 15"].geometry}
            material={materials["gress-3"]}
            castShadow
            receiveShadow
            position={[37.24, 0.21, -319.73]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 14"
            geometry={nodes["Rectangle 14"].geometry}
            material={materials["gress-3"]}
            castShadow
            receiveShadow
            position={[591.93, 0.21, -319.73]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group
          name="spline-tree"
          position={[-177.23, 156.61, -167.49]}
          scale={[1, 1, 1.23]}
        >
          <group
            name="s"
            position={[-191.52, -1.88, -0.14]}
            scale={[1, 1, 0.81]}
          >
            <mesh
              name="tree-3"
              geometry={nodes["tree-3"].geometry}
              material={materials["tree-3 Material"]}
              castShadow
              receiveShadow
              position={[0, 26.75, -3.59]}
              scale={[1, 1, 1.23]}
            />
            <mesh
              name="Cube 51"
              geometry={nodes["Cube 51"].geometry}
              material={materials.wood}
              castShadow
              receiveShadow
              position={[-18.78, 9.15, -5.87]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[1, 1, 1.23]}
            />
            <mesh
              name="Cube 48"
              geometry={nodes["Cube 48"].geometry}
              material={materials.wood}
              castShadow
              receiveShadow
              position={[17.21, -17.75, 5.64]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[1, 1, 1.23]}
            />
            <mesh
              name="tree-2"
              geometry={nodes["tree-2"].geometry}
              material={materials["tree-2 Material"]}
              castShadow
              receiveShadow
              position={[0.5, -1.74, -3.95]}
              scale={[1, 1, 1.23]}
            />
            <mesh
              name="tree-1"
              geometry={nodes["tree-1"].geometry}
              material={materials["tree-1 Material"]}
              castShadow
              receiveShadow
              position={[-2, -26.42, 0]}
              scale={[1, 1, 1.23]}
            />
          </group>
          <mesh
            name="Cube 10"
            geometry={nodes["Cube 10"].geometry}
            material={materials["tree-spline"]}
            castShadow
            receiveShadow
            position={[32.28, -6.41, 1.79]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={1}
          />
          <group name="e" position={[203.14, 0, -1.45]}>
            <mesh
              name="Cube 151"
              geometry={nodes["Cube 151"].geometry}
              material={materials["tree-spline"]}
              castShadow
              receiveShadow
              position={[1.06, -0.62, -3.42]}
              rotation={[0, 0, -Math.PI]}
              scale={1}
            />
            <mesh
              name="Cube 16"
              geometry={nodes["Cube 16"].geometry}
              material={materials["tree-spline"]}
              castShadow
              receiveShadow
              position={[-2.18, 26.14, -2.61]}
              rotation={[0, 0, -Math.PI]}
              scale={1}
            />
            <mesh
              name="Cube 141"
              geometry={nodes["Cube 141"].geometry}
              material={materials["tree-spline"]}
              castShadow
              receiveShadow
              position={[3.35, -25.61, 3.59]}
              rotation={[0, 0, -Math.PI]}
              scale={1}
            />
            <mesh
              name="Cube 142"
              geometry={nodes["Cube 142"].geometry}
              material={materials.wood}
              castShadow
              receiveShadow
              position={[-14.35, -2.64, -1.79]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={1}
            />
          </group>
          <mesh
            name="Cube 71"
            geometry={nodes["Cube 71"].geometry}
            material={materials["tree-spline"]}
            castShadow
            receiveShadow
            position={[-117.4, 9.59, 0.31]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 9"
            geometry={nodes["Cube 9"].geometry}
            material={materials["tree-spline"]}
            castShadow
            receiveShadow
            position={[-29.08, -25.61, 7.91]}
            rotation={[0, 0, -Math.PI]}
            scale={1}
          />
          <mesh
            name="Cube 81"
            geometry={nodes["Cube 81"].geometry}
            material={materials["tree-spline"]}
            castShadow
            receiveShadow
            position={[-52.77, -2.64, -3.24]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 122"
            geometry={nodes["Cube 122"].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[146.82, -29.64, 0.31]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.68, 1, 1.73]}
          />
          <mesh
            name="Cube 13"
            geometry={nodes["Cube 13"].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[106.8, -20.62, 0.31]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[1, 1, 1.73]}
          />
          <mesh
            name="Cube 11"
            geometry={nodes["Cube 11"].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[66.8, -29.64, 0.31]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.68, 1, 1.73]}
          />
          <mesh
            name="Cube 61"
            geometry={nodes["Cube 61"].geometry}
            material={materials.wood}
            castShadow
            receiveShadow
            position={[-131.55, -21.64, 0.31]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={1}
          />
        </group>
        <group name="stone" position={[111.1, 74.89, -23.04]}>
          <mesh
            name="Rectangle 21"
            geometry={nodes["Rectangle 21"].geometry}
            material={materials.stone}
            castShadow
            receiveShadow
            position={[-826.37, -163.93, -478.39]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 101"
            geometry={nodes["Cube 101"].geometry}
            material={materials.stone}
            castShadow
            receiveShadow
            position={[41.65, -37.76, 532.93]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          />
          <mesh
            name="Cube 62"
            geometry={nodes["Cube 62"].geometry}
            material={materials.stone}
            castShadow
            receiveShadow
            position={[-838.6, -59.58, 97.55]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 52"
            geometry={nodes["Cube 52"].geometry}
            material={materials["Cube 52 Material"]}
            castShadow
            receiveShadow
            position={[-725.69, -94.56, 486.31]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 49"
            geometry={nodes["Cube 49"].geometry}
            material={materials.stone}
            castShadow
            receiveShadow
            position={[-244.16, 36.56, -606.39]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 38"
            geometry={nodes["Cube 38"].geometry}
            material={materials.stone}
            castShadow
            receiveShadow
            position={[-911.06, 32.18, -488.54]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 82"
            geometry={nodes["Cube 82"].geometry}
            material={materials.stone}
            castShadow
            receiveShadow
            position={[770.89, -33.44, 272.64]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 72"
            geometry={nodes["Cube 72"].geometry}
            material={materials.stone}
            castShadow
            receiveShadow
            position={[871.6, -67.94, 622.89]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 29"
            geometry={nodes["Cube 29"].geometry}
            material={materials.stone}
            castShadow
            receiveShadow
            position={[-296.11, 21.42, -281.67]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube8"
            geometry={nodes.Cube8.geometry}
            material={materials.stone}
            castShadow
            receiveShadow
            position={[-169.34, -0.95, -319]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="apple" position={[600.3, 151.34, -142.33]}>
          <group
            name="Group 171"
            position={[-958.96, -0.13, 189.12]}
            scale={0.72}
          >
            <mesh
              name="Cube 39"
              geometry={nodes["Cube 39"].geometry}
              material={materials.tree}
              castShadow
              receiveShadow
              position={[7.75, 17.13, -1.91]}
              rotation={[-Math.PI / 2, 0.61, 0]}
              scale={[1.25, 1.67, 1.25]}
            />
            <mesh
              name="Cube 210"
              geometry={nodes["Cube 210"].geometry}
              material={materials["Cube 210 Material"]}
              castShadow
              receiveShadow
              position={[-1.19, 14.73, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.25, 1.67, 1.25]}
            />
            <mesh
              name="Cube9"
              geometry={nodes.Cube9.geometry}
              material={materials.orange}
              castShadow
              receiveShadow
              position={[0, -6.88, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
          <group
            name="Group 16"
            position={[-958.96, -0.13, 267.69]}
            scale={0.72}
          >
            <mesh
              name="Cube 310"
              geometry={nodes["Cube 310"].geometry}
              material={materials.tree}
              castShadow
              receiveShadow
              position={[7.75, 17.13, -1.91]}
              rotation={[-Math.PI / 2, 0.61, 0]}
              scale={[1.25, 1.67, 1.25]}
            />
            <mesh
              name="Cube 211"
              geometry={nodes["Cube 211"].geometry}
              material={materials["Cube 211 Material"]}
              castShadow
              receiveShadow
              position={[-1.19, 14.73, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.25, 1.67, 1.25]}
            />
            <mesh
              name="Cube10"
              geometry={nodes.Cube10.geometry}
              material={materials.orange}
              castShadow
              receiveShadow
              position={[0, -6.88, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
          <group
            name="Group 13"
            position={[-81.14, -0.13, -118.99]}
            scale={0.72}
          >
            <mesh
              name="Cube 311"
              geometry={nodes["Cube 311"].geometry}
              material={materials.tree}
              castShadow
              receiveShadow
              position={[7.75, 17.13, -1.91]}
              rotation={[-Math.PI / 2, 0.61, 0]}
              scale={[1.25, 1.67, 1.25]}
            />
            <mesh
              name="Cube 212"
              geometry={nodes["Cube 212"].geometry}
              material={materials["Cube 212 Material"]}
              castShadow
              receiveShadow
              position={[-1.19, 14.73, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.25, 1.67, 1.25]}
            />
            <mesh
              name="Cube11"
              geometry={nodes.Cube11.geometry}
              material={materials.orange}
              castShadow
              receiveShadow
              position={[0, -6.88, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
          <group name="Group 15" position={[81.14, -1.13, 118.99]} scale={0.72}>
            <mesh
              name="Cube 312"
              geometry={nodes["Cube 312"].geometry}
              material={materials.tree}
              castShadow
              receiveShadow
              position={[7.75, 17.13, -1.91]}
              rotation={[-Math.PI / 2, 0.61, 0]}
              scale={[1.25, 1.67, 1.25]}
            />
            <mesh
              name="Cube 213"
              geometry={nodes["Cube 213"].geometry}
              material={materials["Cube 213 Material"]}
              castShadow
              receiveShadow
              position={[-1.19, 14.73, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.25, 1.67, 1.25]}
            />
            <mesh
              name="Cube12"
              geometry={nodes.Cube12.geometry}
              material={materials.orange}
              castShadow
              receiveShadow
              position={[0, -6.88, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
          <group
            name="Group 14"
            position={[-3.35, -1.13, -118.99]}
            scale={0.72}
          >
            <mesh
              name="Cube 313"
              geometry={nodes["Cube 313"].geometry}
              material={materials.tree}
              castShadow
              receiveShadow
              position={[7.75, 17.13, -1.91]}
              rotation={[-Math.PI / 2, 0.61, 0]}
              scale={[1.25, 1.67, 1.25]}
            />
            <mesh
              name="Cube 214"
              geometry={nodes["Cube 214"].geometry}
              material={materials["Cube 214 Material"]}
              castShadow
              receiveShadow
              position={[-1.19, 14.73, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.25, 1.67, 1.25]}
            />
            <mesh
              name="Cube13"
              geometry={nodes.Cube13.geometry}
              material={materials.orange}
              castShadow
              receiveShadow
              position={[0, -6.88, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
        </group>
        <group name="box-up" position={[378.05, 189.9, 273.19]}>
          <group name="box" position={[0, -30.86, 6.33]} scale={0.74}>
            <group
              name="Group 10"
              position={[-40.07, -0.17, 2.42]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={1}
            >
              <mesh
                name="Rectangle 5"
                geometry={nodes["Rectangle 5"].geometry}
                material={materials["Rectangle 5 Material"]}
                castShadow
                receiveShadow
                position={[-0.2, -22.97, 0.5]}
                scale={[0.87, 0.87, 9.39]}
              />
              <mesh
                name="Shape 15"
                geometry={nodes["Shape 15"].geometry}
                material={materials["Shape 15 Material"]}
                castShadow
                receiveShadow
                position={[-24.98, 7.47, -0.5]}
                scale={[0.87, 0.87, 9.39]}
              />
            </group>
            <group
              name="Group 9"
              position={[40.07, -0.17, -2.42]}
              rotation={[0, Math.PI / 2, 0]}
              scale={1}
            >
              <mesh
                name="Rectangle 51"
                geometry={nodes["Rectangle 51"].geometry}
                material={materials["Rectangle 51 Material"]}
                castShadow
                receiveShadow
                position={[-0.2, -22.97, 0.5]}
                scale={[0.87, 0.87, 9.39]}
              />
              <mesh
                name="Shape 151"
                geometry={nodes["Shape 151"].geometry}
                material={materials["Shape 151 Material"]}
                castShadow
                receiveShadow
                position={[-24.98, 7.47, -0.5]}
                scale={[0.87, 0.87, 9.39]}
              />
            </group>
            <group
              name="Group 101"
              position={[0.42, -0.17, -40.22]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <mesh
                name="Rectangle 52"
                geometry={nodes["Rectangle 52"].geometry}
                material={materials["Rectangle 52 Material"]}
                castShadow
                receiveShadow
                position={[-0.2, -22.97, 0.5]}
                scale={[0.87, 0.87, 9.39]}
              />
              <mesh
                name="Shape 152"
                geometry={nodes["Shape 152"].geometry}
                material={materials["Shape 152 Material"]}
                castShadow
                receiveShadow
                position={[-24.98, 7.47, -0.5]}
                scale={[0.87, 0.87, 9.39]}
              />
            </group>
            <group
              name="Group 11"
              position={[-0.65, 41.19, 2.48]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            >
              <mesh
                name="Rectangle 53"
                geometry={nodes["Rectangle 53"].geometry}
                material={materials["Rectangle 53 Material"]}
                castShadow
                receiveShadow
                position={[-0.2, -22.97, 0.5]}
                scale={[0.87, 0.87, 9.39]}
              />
              <mesh
                name="Shape 153"
                geometry={nodes["Shape 153"].geometry}
                material={materials["Shape 153 Material"]}
                castShadow
                receiveShadow
                position={[-24.98, 7.47, -0.5]}
                scale={[0.87, 0.87, 9.39]}
              />
            </group>
            <group name="Group 8" position={[-0.42, -0.17, 40.22]}>
              <mesh
                name="Rectangle 54"
                geometry={nodes["Rectangle 54"].geometry}
                material={materials["Rectangle 54 Material"]}
                castShadow
                receiveShadow
                position={[-0.2, -22.97, 0.5]}
                scale={[0.87, 0.87, 9.39]}
              />
              <mesh
                name="Shape 154"
                geometry={nodes["Shape 154"].geometry}
                material={materials["Shape 154 Material"]}
                castShadow
                receiveShadow
                position={[-24.98, 7.47, -0.5]}
                scale={[0.87, 0.87, 9.39]}
              />
            </group>
            <mesh
              name="Cube14"
              geometry={nodes.Cube14.geometry}
              material={materials["Cube14 Material"]}
              castShadow
              receiveShadow
              position={[-0.04, 0, -0.11]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
        </group>
        <group name="tree2" position={[118.08, 154.74, 55]}>
          <mesh
            name="Pyramid 6"
            geometry={nodes["Pyramid 6"].geometry}
            material={materials["tree-2"]}
            castShadow
            receiveShadow
            position={[-785.02, 6.75, -374.05]}
          />
          <mesh
            name="Pyramid 4"
            geometry={nodes["Pyramid 4"].geometry}
            material={materials["tree-2"]}
            castShadow
            receiveShadow
            position={[785.02, 8.99, 450.51]}
          />
          <mesh
            name="Pyramid 3"
            geometry={nodes["Pyramid 3"].geometry}
            material={materials["tree-2"]}
            castShadow
            receiveShadow
            position={[-717.87, 6.75, -450.51]}
          />
          <mesh
            name="Pyramid 2"
            geometry={nodes["Pyramid 2"].geometry}
            material={materials["tree-2"]}
            castShadow
            receiveShadow
            position={[-30.6, 3.01, 371.46]}
          />
          <mesh
            name="Pyramid"
            geometry={nodes.Pyramid.geometry}
            material={materials["tree-2"]}
            castShadow
            receiveShadow
            position={[-717.87, 5.96, 229.9]}
          />
        </group>
        <group name="pig 2" position={[286.4, 175.46, -169.82]}>
          <mesh
            name="Rectangle 92"
            geometry={nodes["Rectangle 92"].geometry}
            material={materials["Rectangle 92 Material"]}
            castShadow
            receiveShadow
            position={[5.64, -17.64, 44.48]}
          />
          <mesh
            name="Rectangle 81"
            geometry={nodes["Rectangle 81"].geometry}
            material={materials["Rectangle 81 Material"]}
            castShadow
            receiveShadow
            position={[-7.34, -17.64, 44.48]}
          />
          <mesh
            name="Rectangle 72"
            geometry={nodes["Rectangle 72"].geometry}
            material={materials["pink-2"]}
            castShadow
            receiveShadow
            position={[25.71, 34.26, 17.52]}
          />
          <mesh
            name="Rectangle 63"
            geometry={nodes["Rectangle 63"].geometry}
            material={materials["pink-2"]}
            castShadow
            receiveShadow
            position={[-27.41, 34.26, 17.52]}
          />
          <mesh
            name="Cube 63"
            geometry={nodes["Cube 63"].geometry}
            material={materials["pink-2"]}
            castShadow
            receiveShadow
            position={[35.17, -12.23, 26.95]}
          />
          <mesh
            name="Cube 131"
            geometry={nodes["Cube 131"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[26.02, 37.43, 12]}
          />
          <mesh
            name="Cube 91"
            geometry={nodes["Cube 91"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[-27.1, 37.43, 12]}
          />
          <mesh
            name="Cube 123"
            geometry={nodes["Cube 123"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[20.56, -50.78, -29.06]}
            scale={[1, 1, 1.44]}
          />
          <mesh
            name="Cube 124"
            geometry={nodes["Cube 124"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[-21.99, -50.78, -29.06]}
            scale={[1, 1, 1.44]}
          />
          <mesh
            name="Cube 83"
            geometry={nodes["Cube 83"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[20.56, -50.78, 18.02]}
            scale={[1, 1, 1.44]}
          />
          <mesh
            name="Cube 73"
            geometry={nodes["Cube 73"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[-21.99, -50.78, 18.02]}
            scale={[1, 1, 1.44]}
          />
          <mesh
            name="Cube 53"
            geometry={nodes["Cube 53"].geometry}
            material={materials["pink-2"]}
            castShadow
            receiveShadow
            position={[-35.24, -12.23, 26.95]}
          />
          <mesh
            name="Rectangle 82"
            geometry={nodes["Rectangle 82"].geometry}
            material={materials["Rectangle 82 Material"]}
            castShadow
            receiveShadow
            position={[20.57, 15.57, 35.4]}
            scale={[0.8, 0.25, 1]}
          />
          <mesh
            name="Rectangle 73"
            geometry={nodes["Rectangle 73"].geometry}
            material={materials["Rectangle 73 Material"]}
            castShadow
            receiveShadow
            position={[20.9, 3.53, 35.4]}
          />
          <mesh
            name="Rectangle 83"
            geometry={nodes["Rectangle 83"].geometry}
            material={materials["Rectangle 83 Material"]}
            castShadow
            receiveShadow
            position={[-20.04, 15.57, 35.4]}
            scale={[0.8, 0.25, 1]}
          />
          <mesh
            name="Rectangle 64"
            geometry={nodes["Rectangle 64"].geometry}
            material={materials["Rectangle 64 Material"]}
            castShadow
            receiveShadow
            position={[-20.44, 3.53, 35.4]}
          />
          <mesh
            name="Cube 410"
            geometry={nodes["Cube 410"].geometry}
            material={materials["Cube 410 Material"]}
            castShadow
            receiveShadow
            position={[-0.31, -17.55, 38.89]}
            scale={[0.75, 1, 1]}
          />
          <mesh
            name="Cube 215"
            geometry={nodes["Cube 215"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[-0.11, -8.36, -5.1]}
          />
        </group>
        <group name="chick" position={[-534.81, 171.82, 51.49]}>
          <mesh
            name="Cube 132"
            geometry={nodes["Cube 132"].geometry}
            material={materials["white-2"]}
            castShadow
            receiveShadow
            position={[-39.93, -14.36, -22.18]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 1.23, 1.37]}
          />
          <mesh
            name="Cube 125"
            geometry={nodes["Cube 125"].geometry}
            material={materials["white-2"]}
            castShadow
            receiveShadow
            position={[39.73, -14.36, -22.18]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 1.23, 1.37]}
          />
          <mesh
            name="Cube 133"
            geometry={nodes["Cube 133"].geometry}
            material={materials["white-2"]}
            castShadow
            receiveShadow
            position={[-40.42, 0.37, -16.21]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 1.23, 1.37]}
          />
          <mesh
            name="Cube 111"
            geometry={nodes["Cube 111"].geometry}
            material={materials["white-2"]}
            castShadow
            receiveShadow
            position={[40.42, 0.37, -16.21]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 1.23, 1.37]}
          />
          <mesh
            name="Cube 64"
            geometry={nodes["Cube 64"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[32.36, -11.34, 26.95]}
          />
          <mesh
            name="Cube 102"
            geometry={nodes["Cube 102"].geometry}
            material={materials.red}
            castShadow
            receiveShadow
            position={[-0.14, 48.7, -6.2]}
          />
          <mesh
            name="Cube 92"
            geometry={nodes["Cube 92"].geometry}
            material={materials.red}
            castShadow
            receiveShadow
            position={[-0.14, 40.73, -6.2]}
          />
          <mesh
            name="Cube 84"
            geometry={nodes["Cube 84"].geometry}
            material={materials.orange}
            castShadow
            receiveShadow
            position={[20.56, -48.7, 25.65]}
            scale={[1, 1, 1.44]}
          />
          <mesh
            name="Cube 74"
            geometry={nodes["Cube 74"].geometry}
            material={materials.orange}
            castShadow
            receiveShadow
            position={[-21.99, -48.7, 25.65]}
            scale={[1, 1, 1.44]}
          />
          <mesh
            name="Cube 54"
            geometry={nodes["Cube 54"].geometry}
            material={materials.pink}
            castShadow
            receiveShadow
            position={[-33.98, -11.34, 26.95]}
          />
          <mesh
            name="Rectangle 84"
            geometry={nodes["Rectangle 84"].geometry}
            material={materials["Rectangle 84 Material"]}
            castShadow
            receiveShadow
            position={[22.76, 20.3, 35.4]}
            scale={[0.8, 0.25, 1]}
          />
          <mesh
            name="Rectangle 74"
            geometry={nodes["Rectangle 74"].geometry}
            material={materials["Rectangle 74 Material"]}
            castShadow
            receiveShadow
            position={[23.1, 8.26, 35.4]}
          />
          <mesh
            name="Rectangle 85"
            geometry={nodes["Rectangle 85"].geometry}
            material={materials["Rectangle 85 Material"]}
            castShadow
            receiveShadow
            position={[-21.96, 20.3, 35.4]}
            scale={[0.8, 0.25, 1]}
          />
          <mesh
            name="Rectangle 65"
            geometry={nodes["Rectangle 65"].geometry}
            material={materials["Rectangle 65 Material"]}
            castShadow
            receiveShadow
            position={[-22.36, 8.26, 35.4]}
          />
          <mesh
            name="Cube 411"
            geometry={nodes["Cube 411"].geometry}
            material={materials.orange}
            castShadow
            receiveShadow
            position={[-0.31, -9.29, 34.6]}
            scale={[0.75, 1, 1]}
          />
          <mesh
            name="Cube 314"
            geometry={nodes["Cube 314"].geometry}
            material={materials["Cube 314 Material"]}
            castShadow
            receiveShadow
            position={[-0.31, -3.55, 34.6]}
            scale={[0.75, 1, 1]}
          />
          <mesh
            name="Cube 216"
            geometry={nodes["Cube 216"].geometry}
            material={materials["white-2"]}
            castShadow
            receiveShadow
            position={[-0.11, -5.36, -5.1]}
          />
        </group>
        <group name="tree1" position={[473.59, 178.23, 7.13]}>
          <group
            name="Group 4"
            position={[131.59, -0.06, -364.14]}
            scale={0.84}
          >
            <mesh
              name="Cube 315"
              geometry={nodes["Cube 315"].geometry}
              material={materials.tree}
              castShadow
              receiveShadow
              position={[0, 18.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 217"
              geometry={nodes["Cube 217"].geometry}
              material={materials.wood}
              castShadow
              receiveShadow
              position={[0, -41.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
          <group name="Group 6" position={[430.07, 0.06, 364.14]} scale={0.84}>
            <mesh
              name="Cube 316"
              geometry={nodes["Cube 316"].geometry}
              material={materials.tree}
              castShadow
              receiveShadow
              position={[0, 18.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 218"
              geometry={nodes["Cube 218"].geometry}
              material={materials.wood}
              castShadow
              receiveShadow
              position={[0, -41.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
          <group
            name="Group 41"
            position={[246.84, -0.06, -282.46]}
            scale={0.84}
          >
            <mesh
              name="Cube 317"
              geometry={nodes["Cube 317"].geometry}
              material={materials.tree}
              castShadow
              receiveShadow
              position={[0, 18.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 219"
              geometry={nodes["Cube 219"].geometry}
              material={materials.wood}
              castShadow
              receiveShadow
              position={[0, -41.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
          <group
            name="Group 42"
            position={[-307.38, -0.06, -260.33]}
            scale={0.84}
          >
            <mesh
              name="Cube 318"
              geometry={nodes["Cube 318"].geometry}
              material={materials.tree}
              castShadow
              receiveShadow
              position={[0, 18.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 220"
              geometry={nodes["Cube 220"].geometry}
              material={materials.wood}
              castShadow
              receiveShadow
              position={[0, -41.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
          <group
            name="Group 91"
            position={[-188.9, -0.06, -364.14]}
            scale={0.84}
          >
            <mesh
              name="Cube 319"
              geometry={nodes["Cube 319"].geometry}
              material={materials.tree}
              castShadow
              receiveShadow
              position={[0, 18.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 221"
              geometry={nodes["Cube 221"].geometry}
              material={materials.wood}
              castShadow
              receiveShadow
              position={[0, -41.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
          <group
            name="Group 81"
            position={[-309.84, -0.06, -364.14]}
            scale={0.84}
          >
            <mesh
              name="Cube 320"
              geometry={nodes["Cube 320"].geometry}
              material={materials.tree}
              castShadow
              receiveShadow
              position={[0, 18.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 222"
              geometry={nodes["Cube 222"].geometry}
              material={materials.wood}
              castShadow
              receiveShadow
              position={[0, -41.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
          <group name="Group" position={[-430.07, -0.06, -364.14]} scale={0.84}>
            <mesh
              name="Cube 321"
              geometry={nodes["Cube 321"].geometry}
              material={materials.tree}
              castShadow
              receiveShadow
              position={[0, 18.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 223"
              geometry={nodes["Cube 223"].geometry}
              material={materials.wood}
              castShadow
              receiveShadow
              position={[0, -41.92, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
        </group>
        <group name="sand" position={[-267.48, -8.32, 164.58]}>
          <mesh
            name="Rectangle 2"
            geometry={nodes["Rectangle 2"].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-89.77, -75.02, 567.37]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Rectangle 22"
            geometry={nodes["Rectangle 22"].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[643.92, 42.05, -223.9]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Shape 7"
            geometry={nodes["Shape 7"].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-744.42, -63.72, -376.12]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Shape 155"
            geometry={nodes["Shape 155"].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-442.16, -100, -602.5]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="mountain" position={[-373.66, 96.23, -470.25]}>
          <mesh
            name="Shape 4"
            geometry={nodes["Shape 4"].geometry}
            material={materials.grass}
            castShadow
            receiveShadow
            position={[-338.29, 96.2, -114.12]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Shape 6"
            geometry={nodes["Shape 6"].geometry}
            material={materials.grass}
            castShadow
            receiveShadow
            position={[-338.29, 175.36, -114.12]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Shape 5"
            geometry={nodes["Shape 5"].geometry}
            material={materials.mountain}
            castShadow
            receiveShadow
            position={[-338.48, -185.36, -114.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Shape 3"
            geometry={nodes["Shape 3"].geometry}
            material={materials.mountain}
            castShadow
            receiveShadow
            position={[-338.29, -183.8, -114.12]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="ground" position={[153.25, 11.76, 166.84]}>
          <mesh
            name="Shape 12"
            geometry={nodes["Shape 12"].geometry}
            material={materials["Shape 12 Material"]}
            castShadow
            receiveShadow
            position={[-109.5, 99.14, -77.02]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Shape 13"
            geometry={nodes["Shape 13"].geometry}
            material={materials.grass}
            castShadow
            receiveShadow
            position={[-790.95, 99.34, -453.1]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Shape 2"
            geometry={nodes["Shape 2"].geometry}
            material={materials.grass}
            castShadow
            receiveShadow
            position={[-788.73, 99.34, -451.67]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Shape 14"
            geometry={nodes["Shape 14"].geometry}
            material={materials.ground}
            castShadow
            receiveShadow
            position={[-864.7, -100, -602.61]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <OrthographicCamera
          name="23"
          makeDefault={true}
          zoom={0.49}
          far={100000}
          near={-100000}
          position={[1404.45, 1280.23, 1769.15]}
          rotation={[-0.61, 0.56, 0.36]}
          scale={1}
        />
        <hemisphereLight
          name="Default Ambient Light"
          intensity={0.75}
          color="#f9eef3"
        />
      </group>
    </>
  );
}
